name: flutter_challange
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  fl_chart: ^0.36.1
  country_pickers: ^2.0.0
  diacritic: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Karla
      fonts:
        - asset: assets/Karla-Bold.ttf
          weight: 900
        - asset: assets/Karla-Regular.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.otf
          weight: 500
        - asset: assets/Poppins-Medium.otf
          weight: 700
        - asset: assets/Poppins-Light.otf
          weight: 300

